//
//  RegionAddModels.swift
//  WriteMe
//
//  Created by Vladimir on 13.11.2020.
//  Copyright (c) 2020 Vladimir Mikhaylov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RegionAdd
{
    struct RegionFormFields
    {
        var name: String?
        var phoneCode: String?
    }
    // MARK: Use cases
    enum Setup
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
    
    enum Save
    {
        struct Request
        {
            var regionFormFields: RegionFormFields
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
    }
}
