//
//  RegionAddRouter.swift
//  WriteMe
//
//  Created by Vladimir on 13.11.2020.
//  Copyright (c) 2020 Vladimir Mikhaylov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RegionAddRoutingLogic {
    func routeToRegionsSelector()
}

protocol RegionAddDataPassing {
    var dataStore: RegionAddDataStore? { get }
}

class RegionAddRouter: NSObject, RegionAddRoutingLogic, RegionAddDataPassing {

    weak var viewController: RegionAddOLDViewController?
    var dataStore: RegionAddDataStore?

    // MARK: Routing

    func routeToRegionsSelector() {
        guard let viewController = viewController else { return }
        guard let dataStore = dataStore else { return }
        guard let destinationVC = viewController.navigationController?.previousViewController as? RegionSelectorViewController else { return }
        guard var destinationDS = destinationVC.router?.dataStore else { return }
        passDataToRegionsSelector(source: dataStore, destination: &destinationDS)
        navigateToRegionsSelector(source: viewController, destination: destinationVC)
    }

    // MARK: Navigation

    func navigateToRegionsSelector(source: RegionAddOLDViewController, destination: RegionSelectorViewController) {
        source.navigationController?.popViewController(animated: true)
    }

    // MARK: Passing data

    func passDataToRegionsSelector(source: RegionAddDataStore, destination: inout RegionSelectorDataStore) {

    }
}
