//
//  RegionAddInteractor.swift
//  WriteMe
//
//  Created by Vladimir on 13.11.2020.
//  Copyright (c) 2020 Vladimir Mikhaylov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegionAddBusinessLogic
{
  func doSomething(request: RegionAdd.Something.Request)
}

protocol RegionAddDataStore
{
  //var name: String { get set }
}

class RegionAddInteractor: RegionAddBusinessLogic, RegionAddDataStore
{
  var presenter: RegionAddPresentationLogic?
  var worker: RegionAddWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: RegionAdd.Something.Request)
  {
    worker = RegionAddWorker()
    worker?.doSomeWork()
    
    let response = RegionAdd.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
