//
//  RegionAddViewController.swift
//  WriteMe
//
//  Created by Vladimir on 13.11.2020.
//  Copyright (c) 2020 Vladimir Mikhaylov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegionAddDisplayLogic: class {
    var contentView: RegionAddView { get }
    func setup(viewModel: RegionAdd.Setup.ViewModel)
    func save(viewModel: RegionAdd.Save.ViewModel)
}

class RegionAddOLDViewController: UIViewController, RegionAddDisplayLogic {
    internal lazy var contentView = RegionAddView()
    var interactor: RegionAddBusinessLogic?
    var router: (NSObjectProtocol & RegionAddRoutingLogic & RegionAddDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        let viewController = self
        let interactor = RegionAddOLDInteractor()
        let presenter = RegionAddOLDPresenter()
        let router = RegionAddRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
        setupView()
    }

    private func setupView() {
        navigationController?.navigationBar.prefersLargeTitles = false
        navigationItem.title = NSLocalizedString("RegionAdd", comment: "")
        navigationItem.rightBarButtonItem = UIBarButtonItem(title: NSLocalizedString("Save", comment: ""),
                                                            style: .plain,
                                                            target: self,
                                                            action: #selector(saveClicked))
    }

    // MARK: View lifecycle

    override func loadView() {
        view = contentView
    }

    override func viewDidLoad() {
        super.viewDidLoad()

    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        setupData()
    }

    func setupData() {
        interactor?.setup(request: RegionAdd.Setup.Request())
    }

    func setup(viewModel: RegionAdd.Setup.ViewModel) {
    }

    func save(viewModel: RegionAdd.Save.ViewModel) {
        router?.routeToRegionsSelector()
    }

    @objc private func saveClicked() {
        let name = contentView.nameInputView.inputTextField.text
        let phoneCode = contentView.codeInputView.inputTextField.text
        interactor?.save(request: RegionAdd.Save.Request(regionFormFields: RegionAdd.RegionFormFields(name: name, phoneCode: phoneCode)))
    }
}
