//
//  RegionAddPresenter.swift
//  WriteMe
//
//  Created by Vladimir on 13.11.2020.
//  Copyright (c) 2020 Vladimir Mikhaylov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import InputMask

protocol RegionAddPresentationLogic
{
    func setup(response: RegionAdd.Setup.Response)
    func save(response: RegionAdd.Save.Response)
}

class RegionAddPresenter
{
    weak var viewController: RegionAddDisplayLogic?
    var listener = MaskedTextFieldDelegate()
    
    // MARK: Do something
    
}
    
    
extension RegionAddPresenter: RegionAddPresentationLogic {
    
    func setup(response: RegionAdd.Setup.Response) {
        listener.primaryMaskFormat = "+[000000000000000000000000]"
        viewController?.contentView.codeInputView.inputTextField.delegate = listener
    }
    
    func save(response: RegionAdd.Save.Response) {
        viewController?.save(viewModel: RegionAdd.Save.ViewModel())
    }
    
}
