//
//  RegionSelectorPresenter.swift
//  WriteMe
//
//  Created by Vladimir Mikhaylov on 03.10.2020.
//  Copyright (c) 2020 Vladimir Mikhaylov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegionSelectorPresentationLogic
{
    func fetchRegions(response: RegionSelector.FetchRegion.Response)
    func saveRegion(response: RegionSelector.SaveRegion.Response)
}

class RegionSelectorPresenter: RegionSelectorPresentationLogic
{
  weak var viewController: RegionSelectorDisplayLogic?
}

extension RegionSelectorPresenter
{
    func fetchRegions(response: RegionSelector.FetchRegion.Response)
    {
      let viewModel = RegionSelector.FetchRegion.ViewModel(regions: response.regions)
      viewController?.fetchRegions(viewModel: viewModel)
    }
    
    func saveRegion(response: RegionSelector.SaveRegion.Response)
    {
        let viewModel = RegionSelector.SaveRegion.ViewModel()
        viewController?.saveRegion(viewModel: viewModel)
    }
}
